#!/bin/bash

# Get the script directory
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Add the script directory to the PATH
export PATH=$PATH:$SCRIPT_DIR

# Run the Python script
python3 "$SCRIPT_DIR/convert_postman_to_csv.py"
